# Generated by Django 3.2b1 on 2021-03-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('bid', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=200)),
                ('bpub_date', models.DateField(blank=True, null=True)),
                ('bread', models.IntegerField()),
                ('bcomment', models.IntegerField()),
                ('bimage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password_hash', models.CharField(db_column='password', max_length=20)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_drf',
            },
        ),
        migrations.CreateModel(
            name='Heroinfo',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='drf.bookinfo')),
            ],
            options={
                'db_table': 'heroinfo',
            },
        ),
    ]
