# Generated by Django 3.2b1 on 2021-03-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=200)),
                ('bpub_date', models.DateField(blank=True, null=True)),
                ('bread', models.IntegerField()),
                ('bcomment', models.IntegerField()),
                ('bimage', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='Heroinfo',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=50)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drf.bookinfo')),
            ],
            options={
                'db_table': 'heroinfo',
            },
        ),
    ]
