# Generated by Django 3.2b1 on 2021-03-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'goods',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('ssex', models.CharField(default='男', max_length=2, null=True)),
                ('sage', models.IntegerField(null=True)),
                ('sclass', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('buyer', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='myApp.buyer')),
                ('goods', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='myApp.goods')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='buyer',
            field=models.ManyToManyField(through='myApp.Orders', to='myApp.Buyer'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.ForeignKey(db_column='pid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='myApp.publisher')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.CharField(max_length=18, unique=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.student')),
            ],
            options={
                'db_table': 'archives',
            },
        ),
    ]
