# Generated by Django 3.1.6 on 2021-02-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gName', models.CharField(max_length=20)),
                ('gDate', models.DateTimeField()),
                ('gGirlNum', models.IntegerField()),
                ('gBoyNum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('sGender', models.BooleanField(default=True)),
                ('sAge', models.IntegerField()),
                ('sContEnd', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('sGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.grades')),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-id'],
            },
        ),
    ]
