# Generated by Django 3.2b1 on 2021-03-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('buyer', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='myApp.buyer')),
                ('goods', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='myApp.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='buyer',
            field=models.ManyToManyField(through='myApp.Orders', to='myApp.Buyer'),
        ),
    ]
