# Generated by Django 3.1.6 on 2021-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='lastTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
