# Generated by Django 3.2b1 on 2021-03-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20210302_1748'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyer',
            table='buyer',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
