# Generated by Django 3.1.6 on 2021-02-25 09:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210225_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', tinymce.models.HTMLField()),
                ('timestamp', models.DateTimeField()),
                ('auth', models.TextField(default='鲁迅')),
                ('address', models.CharField(default='北京', max_length=100)),
            ],
        ),
    ]
